language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: CLHxHyL/d04CnhIlw4p/5fsKg6n2zUcic+er7EOAHhev9At7BVbSB/WtDWgqcSbf7Whz1HbCl0JAlQJu/ARISAt5NSzJleCGWQ4IUsfI7C2qRQJScnGq8Olx5hmZ2ne3gAp1qKVdHvpUYl5uA9To98Lkm0NV9dsx1Vw9Mqks/N5Q1pCOjDZusNQ1+GqgD7x3RUdDlg0fNkZFGpDhgR6TGxApJed1l9HJ8OP18pJZi6//a3a2OezUfYT5vC3OQ0oGF2f1Mv55j0W0ME+9/SxgT1N6Q3goqVE4/SXl783eExUsQ/TxTu57nWQHdz+P54mdOhukJjG4U4zG3sEe56XsMVxrK53c3SYAVXVqSfb5gbflLV2T+dRaoEhV6oTBNiFi/vs1SfG+50BDXuSdmNU/3OOFUDRw6h/rj2Ui/PRMmxe24LPQbDBR5WPmKigjQcfFDrNl84r0vINjKvTgY/G1U/ma8MWvfARgDoVy+oAK9/jj4MhH+2VEpo0jQ6210Aw3xGFv96NnEw9SYLkh83NoLaFJt+uTH/SoJy+pmRvkvoP1AKi+i5SRbOmVZZ2ZDauwKdP0F+c0tw3o2Csgo5BP2E2OO90LTwQegZ75Sjja1ZT0TPbH2dKHxFV2M94vr9NU0VCV4QsQaMwYKxzpVfdsZjpQkFUwZ+errpnejfy1500=
  app: tranquil-inlet-36474
  on:
    repo: RoundEm/Clash_for_the_Cup_back-end
