language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: DTdPGQOHlsF6qCxUZD/uVnBjSZUL7XT7r8piFRbHGhYIRWhA2pl/qbu+OhtIFmw6DxCSlJCUQr2KiM6ZCvwHLg8XUJ7DIcGEokQrTi7s/vxyyPiIF7YlfHs+EAl90DZ7nqXtckAJo9SmCcyThq855s7s+kaCRlrHzyYwlNv7N72LLZ0LCciDJNKLtOs+5jTjnzHeYAl55Jh6fo3x4DI5fL86GLjIni8pbt598i0pELUmU54/Tuhyluq9vQvEhfLmAMPy/YZFRlJVunVFG5VveuL8gTHfsWJeeNiZPqHLVb6Dgi7j9rlBegmqzZy9B3SjAGgR0MoUkGG1WpypOAMPzXkTa9/pxLwGpwRa8gnyK+kmuw1loi+APb1FgDPqKFOd3H+ZWjC5eiSvVHqiYW+2ioepjKujG6HE1d6kajlVBNYyN9kZVEbj7FOQdgoX0PyvKzmXpbyXaOcsUeC9l1FGc3xcM5x4y6KZq2ph9n4unm5Ue1Riy2VMMEAerPDXNOyyuOyaa8yoTCp+MqAcJORYkQormApw0x3ZEUh941IXzUszuBhk8OpFaNXC637z97dy7eBTlNN22qbVU4QtfKcyHSGkt6pydBs0iVDQTIhjtbicfqLTcA8GjOtcF0w42qiGr7ePK93q9RCD28cRxRGIF82U4IShrvdmJ/9CSvVa3wA=
  app: infinite-hamlet-47856
  on:
    repo: RoundEm/Clash_for_the_Cup_back-end
