language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: dpgCyunHE3YBfTOjEcPCO4l8rV5kj5rtNOAuOETENLnMJ7QwxlLaehvp/2D+eMO+A3aGlB/aG28G4MpGlQKiZTFbh61ZcSCF+AZGNA+DFIaNukhrXMCmbuV7HjJY43GWBWjbiAjAEUEynUJ42blG3c5I9wR1Q6lqC2HyikZSrFPc/0NmoSPAzD8lSGcqMY1A9rgItf2TQN/LVZv85l1ecnscqKcKN5tThTrtHnnhpdI/pelASDBMNOdrQWNevzhFRPFxUkCXTVM7pF8BAQxgk140htRY3LYCQSS6dfkvTWWcwIXtriprIDag+tIXPkSnZMBkZTk+EUwljhr1imvUqmn8YRWHMa+qkbjd28+3Dl1VlosAlHZ17yiobeOHFC29JAe+iqdRFscmHOTCVlR09/3WS6X8R38vBj52x+NBNLkwo1Emp9gq2Rb3o6xhNT7p53PfgtufBBmW5svrlpdClbHz1BmGw0kxUY9nuRh29XladC4GFMTm0XMx3XfO3NhLIoaU3HwpDK3Peg/FHodTenLky9f/S7nmV1j+vMmLLNX19faNBsNwk5mOY5jAdvgEfNGyZNtR/jiEM1Xmg8ccnWJXvB24ZVTgaJou/5Gb0+xXt7xPUieTAtRwy4EkROQJZRWNN8QFLZYJuw2nMF0aCKWNWAasHpYYGZHjD42R7Do=
  app: guarded-shore-66749
  on:
    repo: RoundEm/Clash_for_the_Cup_back-end
